<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Microsoft.Demo.HttpProxy.Handler</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Demo.HttpProxy.Routing\Microsoft.Demo.HttpProxy.Routing.csproj" />
    <Reference Include="Microsoft.Demo.Data.Common" />
  </ItemGroup>
</Project>
